name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # 1. Clona o repositório de testes
      - name: Checkout cypress-rwa-tests
        uses: actions/checkout@v4

      # 2. Configura a versão do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Clona, instala dependências e inicia o RWA (Front na 3000 e Back na 3001)
      - name: Setup and Start RWA App
        run: |
          git clone https://github.com/cypress-io/cypress-realworld-app.git
          cd cypress-realworld-app
          yarn install
          yarn dev &
          npx wait-on http://localhost:3000 http://localhost:3001

      # 4. Executa a suíte de testes do Cypress
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: .

      # 5. Salva screenshots em caso de falhas
      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots